[phases.setup]
nixPkgs = [
  "php",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.simplexml",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:cache",
  "php artisan view:clear"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
